name: webooks
description: "중고도서 판매 플랫폼 - joongobooks version 2."
publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  dio: ^5.4.0

  flutter_dotenv: ^6.0.0

  flutter_secure_storage: ^8.0.0

  kakao_flutter_sdk_user: ^1.6.1
  googke_sign_in: '>=6.0.0 <7.0.0'

  flutter_svg: ^2.2.3
  cache_network_image: ^3.4.1
  shimmer: ^3.0.0

  intl: ^20.2
  url_launcher: ^6.1.10

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.0
  riverpod_generator: ^3.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/images/


  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700